### ISSUE TITLE
Dev Project Membership in Inconsistent State

### ISSUE THREAD

**Issue by devinsm** [MSD-LIVE/issues#153]
To reproduce this issue:
1. Go to dev.msdlive.org
2. Log in as admin@msdlive.org
3. Go to https://dev.msdlive.org/projects/cats-dev/current
4. Try to add or remove a role from one of the members
5. The request will fail with a 502 error. Checking the Sentry logs you see the error on the server was: https://pnnl-l9.sentry.io/issues/4634213417/?environment=DEV&project=4503972881629184&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

This appears because in the RDM database the user was not in the project. Checking the Cognito user pool for the dev site, I see that the users are in the correct groups in Cognito.

The question is, how did things get out of sync?

**Comment by devinsm** [comment]
@zguillen and @clansing What do you guys thing about this?

**Comment by zguillen** [comment]
yea, it's way off...  take a look at the members RDM thinks it has:
https://data.dev.msdlive.org/communities/08b2be74-f19c-4143-9f67-29b49b9ba4f7/members?q=&l=list&p=1&s=25&sort=name 
 Maybe while working on the refactored UI part of the request failed?

**Comment by zguillen** [comment]
Appears all of the projects' members are out of sync between RDM and cognito.

**Comment by devinsm** [comment]
OK, yeah maybe something in the code was broken and it added them to Cognito and not to RDM. I'll play around with it a bit just to make sure that's not still happening.

**Comment by devinsm** [comment]
It seems to be working now. I added myself and changed my role, and the changes were reflected in RDM. I'll get things back in sync and then close this issue.

**Comment by devinsm** [comment]
I went ahead and removed everyone from the out of sync projects. To add people back in, we can log in as admin@msdlive.org. It wasn't just cats. Two other projects (fish and dogs) were also out of sync. Really not sure what happened.
