### ISSUE TITLE
landing page CLI installer download link endless spinning

### ISSUE THREAD

**Issue by zguillen** [MSD-LIVE/issues#160]
I almost always see this when I go to the cli help page from the dataset's modal but renders correctly after I refresh the page:

![Image](https://github.com/MSD-LIVE/issues/assets/1569461/6f4a30bf-8833-45a5-914f-f0c7d37ad267)

![Image](https://github.com/MSD-LIVE/issues/assets/1569461/28b6a31f-02ac-48d2-90ca-7f2ee2379ad9)

**Comment by ghost** [comment]
This was fixed
