### ISSUE TITLE
login/out button (tippy top right of both sites) state isn't always correct

### ISSUE THREAD

**Issue by zguillen** [MSD-LIVE/issues#163]
often when i log out or log in the component at the tippy top right doesn't correctly reflect the current state. I'll have to navigate to the landing page from rdm before it shows the correct state when logging in from RDM. Or, when I log out when on the landing page app I'll have to nav to rdm and back before it'll show that i'm logged out. (i was on the project members page and clicked log out then this was shown):

![Image](https://github.com/MSD-LIVE/issues/assets/1569461/ae36cd03-2122-4f43-ad85-d38e3ce596af)

**Comment by zguillen** [comment]
@devin-pnnl also a side question/potential issue: is it expected that the page not found component is rendered when logging out from a project members page? or is that a bug with the new code? fine by me if its expected, just wanted to mention

**Comment by ghost** [comment]
@zguillen I think the "Not Found" error is also a bug. I can work on figuring out what's going wrong.

**Comment by ghost** [comment]
This was fixed
