### ISSUE TITLE
Users Can't Approve/Cancel/Decline When Width is Specific Value

### ISSUE THREAD

**Issue by ghost** [MSD-LIVE/issues#186]
![Screenshot 2024-04-30 at 1 15 37 PM](https://github.com/MSD-LIVE/issues/assets/153538814/8344ac0f-2202-4d5f-b325-a3260104ae61)
![Screenshot 2024-04-30 at 1 15 50 PM](https://github.com/MSD-LIVE/issues/assets/153538814/eb7a1879-aeb2-4d19-b42c-6f5ec6462a9a)
![Screenshot 2024-04-30 at 1 16 00 PM](https://github.com/MSD-LIVE/issues/assets/153538814/78abd9fd-719d-4a19-83a9-e89b6bbe7f79)

At specific width the buttons disappear.

**Comment by jugovimm** [comment]
I reviewed this ticket; bug no longer exists and has been corrected in the UI; closing issue
