### ISSUE TITLE
add time slider to launches metrics

### ISSUE THREAD

**Issue by zguillen** [MSD-LIVE/issues#230]
Looks like we need this slider:
![Image](https://github.com/user-attachments/assets/68a68361-ea82-4237-8f81-4736f753685b)

added to the launches metrics since we have that huge spike now that makes it difficult to see how many launches there are on 'normal' days: 
![Image](https://github.com/user-attachments/assets/caad6b0a-2283-4eda-ba11-a2df5336cb42)

**Comment by AndreAmantePNNL** [comment]
https://github.com/MSD-LIVE/landing-page/pull/81
